### ISSUE TITLE
Error somewhere in the Setup

### ISSUE THREAD

**Issue by leaneb** [EIDA/eidaws-federator-deployment#10]
Hi Daniel

Currently i'm dealing either with an Bad Request or Internal Server Error issue when i terminate SSL Connections on the Frontend Proxy.. and made a request to my test federator. Sadly i don't find the exact Erorr either in Nginx Log of the Frontend or End Point Proxy. And good idear?

**Comment by damb** [comment]
Hi @leaneb,

it's difficult to give any advice if I don't see any code/configuration.

Some hints on how to debug, e.g.:
- Does the *traditional request*  over HTTP still work? Although, building the images is successful, there might still be dependency issues due to e.g. changing APIs etc.
- Check the logs via e.g. [`docker logs`](https://docs.docker.com/engine/reference/commandline/logs/)
- Besides, application logs are stored within the containers under `/var/log/eidaws/`

**Comment by damb** [comment]
@leaneb, I checked the HTTP implementation and fixed some of the dependency issues. See #11.

**Comment by damb** [comment]
Though, at the time being, `eidaws-federator`'s backend is not fully prepared to cope with HTTPS. (This would be required in order to use HTTPS based routing URLs. See also https://github.com/EIDA/etc/issues/36#issuecomment-1057676337.)

Therefore, I'm going to implement https://github.com/EIDA/eidaws/issues/28 as a temporary solution. With that, we should be able to terminate HTTPS connections at `eidaws-federator`'s frontend reverse proxy.

**Comment by damb** [comment]
@leaneb, with #12 the deployment should be ready to cope with HTTPS `eidaws-routing` URLs (i.e. `eidaws-federator` backend-wise). Additionally, with #11 the HTTP stuff should be fixed, again. 

Could you please test the current deployment on your side? Thanks.
